# Rotate left is broken for some reason now. Set it in .xinitrc

# Monitor 2
Section "Monitor"
    Identifier   "DP-6"
    Option	 "ignore" "true"
EndSection

# Monitor 3
Section "Monitor"
    Identifier   "DP-5"
    Option       "RightOf" "DP-3"
EndSection

# Monitor 5
Section "Monitor"
    Identifier   "DP-4"
    Option       "RightOf" "DP-5"
    Option	 "ignore" "true"
EndSection

# Monitor 1
Section "Monitor"
    Identifier   "DP-3"
EndSection

# Montitor 4
Section "Monitor"
    Identifier   "DP-2"
    Option       "RightOf" "DP-5"
EndSection

Section "Device"
    Identifier   "Device0"
    Option       "Monitor-DP-6" "DP-6"
    Option       "Monitor-DP-5" "DP-5"
    Option       "Monitor-DP-4" "DP-4"
    Option       "Monitor-DP-3" "DP-3"
    Option       "Monitor-DP-2" "DP-2"
EndSection
