Section "Monitor"
    Identifier "VGA"
    Modeline "2880x1800" 442.00 2880 3104 3416 3952 1800 1803 1809 1865 -hsync +vsync
    Option "PreferredMode" "1280x1800"
EndSection

Section "Screen"
    Identifier "Primary"
    Monitor "VGA"
    SubSection "Display"
        Depth 24
        Modes "2880x1800"
    EndSubSection
EndSection
