# Rotate left is broken for some reason now. Set it in .xinitrc

# Monitor 2
Section "Monitor"
    Identifier   "DP-1"
EndSection

# Monitor 3
Section "Monitor"
    Identifier   "DP-2"
    Option       "LeftOf" "DP-1"
EndSection

# Monitor 5
Section "Monitor"
    Identifier   "DP-3"
    Option       "RightOf" "DP-1"
EndSection

Section "Device"
    Identifier   "Device0"
    Option       "Monitor-DP-1" "DP-1"
    Option       "Monitor-DP-2" "DP-2"
    Option       "Monitor-DP-3" "DP-3"
EndSection
