#!/bin/bash
killall -9 \
  sxhkd \
  unclutter \
  urxvtd \
  nextcloud \
  polybar

sxhkd &
unclutter --timeout 1 &
urxvtd -q -f
$HOME/.config/polybar/launch.sh
nextcloud &

if [ "$(hostname)" == "desktop-arch" ]; then
  bspc monitor DP-3 -d 1 2 3
  bspc monitor DP-5 -d 4 5 6
  bspc monitor DP-2 -d 7 8 9
  bspc rule -a Chromium desktop="^7"
  bspc rule -a Firefox desktop="^7"
  bspc rule -a KeePass2 desktop="^9"
elif [ "$(hostname)" == "mbp-arch" ]; then
  bspc monitor -d I II III IV V VI VII VIII IX X
  bspc rule -a Chromium desktop="^1"
  bspc rule -a Navigator desktop="^1"
  bspc rule -a KeePass2 desktop="^10"
fi

bspc config border_width               1
bspc config window_gap                 10
bspc config top_padding                0

bspc config split_ratio                0.5
bspc config borderless_monocle         true
bspc config gapless_monocle            true

bspc config automatic_scheme           longest_side

bspc config normal_border_color        \#282828
bspc config active_border_color        \#b8bb26
bspc config focused_border_color       \#b8bb26

