#!/bin/bash

STARTUP=(\
  sxhkd
  xss-lock
  protonmail-bridge
  unclutter
  nextcloud
  polybar
  dunst
  vmware-user
  # picom
  feh
)

for app in ${STARTUP[@]}; do
  PID=$(pidof $app)
  if [ ! -z $PID ]; then
    kill -9 $PID
    echo $PID
  fi
done

unclutter --timeout 1 & # Hide mouse arrow
$HOME/.config/polybar/launch.sh # Launch Polybar
nextcloud & # Launch Nextcloud
dunst &
# picom & # Window compositor
sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &
xss-lock -- /usr/bin/i3lock --nofork --no-unlock-indicator --color=000000 &
protonmail-bridge --noninteractive &

bspc monitor DP-2 -d 1 2
bspc monitor DP-1 -d 3 4 5 6
bspc monitor DP-3 -d 7 8 9 10
bspc desktop -f 3

bspc config window_gap 1
bspc config border_width 1
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config automatic_scheme longest_side
bspc config pointer_follows_focus true
bspc config normal_border_color \#282828
bspc config active_border_color \#282828
bspc config focused_border_color \#83a598
