#!/bin/bash

STARTUP=(\
  sxhkd
  unclutter
  urxvtd
  nextcloud
  polybar
  vmware-user
  # picom
  feh
)

for app in ${STARTUP[@]}; do
  PID=$(pidof $app)
  if [ ! -z $PID ]; then
    kill -9 $PID
  fi
done

feh -bg-color red # Background image
unclutter --timeout 1 & # Hide mouse arrow
urxvtd -q -f # Daemonize urxvt
$HOME/.config/polybar/launch.sh # Launch Polybar
nextcloud & # Launch Nextcloud

if [ "$(hostname)" == "desktop-arch" ]; then
  # picom & # Window compositor
  sxhkd -c "$HOME/.config/sxhkd/desktop-arch-sxhkdrc" &
  bspc monitor DP-2 -d 1 2
  bspc monitor DP-1 -d 3 4 5 6
  bspc monitor DP-3 -d 7 8 9 10
  bspc config window_gap                 2
  bspc desktop -f 3
  bspc rule -a Chromium desktop="^1"
  bspc rule -a firefox desktop="^1"
  bspc rule -a KeePass2 desktop="^6"
elif [ "$(hostname)" == "mbp-arch" ]; then
  vmware-user # For VMWare Fusion
  sxhkd -c "$HOME/.config/sxhkd/mbp-arch-sxhkdrc" &
  bspc monitor -d I II III IV V VI VII VIII IX X
  bspc config window_gap                 4
  bspc rule -a Chromium desktop="^1"
  bspc rule -a firefox desktop="^1"
  bspc rule -a KeePass2 desktop="^10"
fi

bspc config border_width               2

bspc config split_ratio                0.5
bspc config borderless_monocle         true
bspc config gapless_monocle            true

bspc config automatic_scheme           longest_side
bspc config pointer_follows_focus      true

bspc config normal_border_color        \#000000
bspc config active_border_color        \#000000
bspc config focused_border_color       \#689d6a

bspc config single_monocle             true
