general.import = [
  "~/.config/alacritty/platform.toml",
]

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font"

[window]
padding.x = 14
padding.y = 14

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" }
]
